---
title: "data recording"
author: "Tracy_Ji"
date: "01/06/2021"
output: html_document
---


## Import and Transform relig-income file
```{r}
library(tidyverse)
library(readxl)
rel_inc <- read_excel("relig-income.xlsx") 
rel_inc_long <- rel_inc %>%
  rename(
    religion = `Religious tradition`,
    n = `Sample Size`
  ) %>%
  pivot_longer( 
    cols = -c(religion, n),   # all but religion and n 
    names_to = "income",  
    values_to = "proportion" 
  ) %>%
    mutate(frequency = round(proportion * n))
```

## Visualization using barplot
```{r}
ggplot(rel_inc_long, aes(y = religion, x = frequency)) +
  geom_col()
rel_inc_long <- rel_inc_long %>%
  mutate(religion = case_when(
    religion == "Evangelical Protestant"           ~ "Ev. Protestant",
    religion == "Historically Black Protestant"    ~ "Hist. Black Protestant",
    religion == 'Unaffiliated (religious "nones")' ~ "Unaffiliated",
    TRUE                                           ~ religion
  ))
rel_inc_long <- rel_inc_long %>%
  mutate(religion = fct_rev(religion))

ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) + 
  geom_col()

```

##Legend Adjustment
```{r}
ggplot(rel_inc_long, aes(y = religion, x = frequency, fill = income)) +
  geom_col(position = "fill") +
  scale_fill_viridis_d() +
  theme_minimal() +
  theme(legend.position = "bottom") +
  guides(fill = guide_legend(nrow = 2, byrow = TRUE))
```

