---
title: Fun with R
author: ''
date: '2021-05-25'
slug: fun-with-r
categories:
  - basics
tags: []
---

## Variables and Numbers

```{r}
x <- 1
y = 2
3 -> z
x + y
y*z
y/z
```


## Vectors
```{r}
a <- 0:10
print(a)
b<- 10:-4
print(b)
class(a)
str(a)
a[c(1,5,7,8)]
head(a)
tail(b,5)
```

## Combine Operator for creating vectors
When we create a vector with multiple data types, R coerces vector to the most compatible data type.

```{r}
c <- c(1,2,4)
print(c)
c <-c(1,7:9)
print(c)
c <- c("red", "green", "yellow")
print(c)
c <-c(1:5, 10.5, "red")
print(c)
class(c)
str(c)
d <- c(1:5, 10.5)
print(d)
class(d)
str(d)
```

## Create Vector Using seq

```{r}
seq(3, 20,3)
seq(1,9, by = 2)
seq(from=4.5, to=2.5,by = -0.2)

```

## Application of Seq

```{r}
x<-seq(0, 8*pi, length.out = 200)
y <- sin(x)
plot(x, y)
```

## Accessing Vector Elements
```{r}
a[5:8]
a[5:3]

```


## Dropping Missing Values
```{r}
a<-c(3,-2,4,NA,-1,8,-4,9,NA, 11,3,8,NA);
a[!is.na(a)]
```

## Summarizing values
```{r}
a <-c(2,3,-1,3,5,2,-3,1)

print(paste0("The sum of positive integers in a = ", sum(a[a>0])))
```

## Matrix
```{r}
M1 <- matrix(1:12, ncol = 4, byrow = TRUE)
M1
M1[2,]
M2 <- matrix(1:12, nrow = 4)
M2
```

##Accessing matrix elements

```{r}
a <- matrix(1:20, ncol = 4)
a
a[c(3,5), c(2,4)]
```

## Creating Data Frame
```{r}
DF <- data.frame(
gender = c("Male", "Male","Female"),
height = c(152, 171.5, 165),
weight = c(81,93, 78),
age =c(42,38,26),
row.names=c('Ally','Belinda','Alfred')
)
DF
DF$gender = "Male"

```

